# theme = "dark_plus"
theme = "carbonfox"
# theme = "flexoki_dark"
# theme = "nightfox"
# theme = "seoul256-dark"
# theme = "everforeset_dark" # I dont like how it highlights comments and imports. So big and blocky :(

[editor]
end-of-line-diagnostics = "hint"
line-number = "relative"
# evil = true
scrolloff = 10
cursorline = true
completion-timeout = 100
color-modes = true
auto-pairs = false

[editor.statusline]
left = ["mode", "spacer", "version-control", "file-name", "read-only-indicator", "file-modification-indicator", "spinner"]
center =[]
right = ["diagnostics", "primary-selection-length", "position", "position-percentage", "spacer", "file-encoding"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.lsp]
display-messages = true
display-inlay-hints = true
display-progress-messages = true

#[editor.inline-diagnostics]
#cursor-line = "warning"

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.auto-save]
after-delay.enable = true
after-delay.timeout = 2000

[keys.normal]
C-q = ":q"
C-v = ":vsplit"
C-s = ":hsplit"
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"

