theme = "dark_plus"
# theme = "carbonfox"
# theme = "flexoki_dark"
# theme = "nightfox"

[editor]
end-of-line-diagnostics = "hint"
line-number = "relative"
# evil = true
scrolloff = 10
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.lsp]
display-messages = true
display-inlay-hints = true

#[editor.inline-diagnostics]
#cursor-line = "warning"

[editor.auto-save]
after-delay.enable = true
after-delay.timeout = 2000

[keys.normal]
C-q = ":q"
C-v = ":vsplit"
C-s = ":hsplit"
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"

[editor.clipboard-provider.custom]
yank = { command = "cb",  args = ["copy"] }
paste = { command = "cb",  args = [] }
